kind: Service
apiVersion: v1
metadata:
  name: test-service
  namespace: nostradamus
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: port-service
  selector:
    app: test-app
  #loadBalancerIP: 10.0.0.10

